name: personal_website
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_dotenv: ^5.0.2
  flutter_svg: ^2.0.5
  get_it: ^7.3.0
  googleapis: ^11.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.5
  http_interceptor: ^1.0.2
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Product Sans
      fonts:
        - asset: assets/font/product-sans-bold-italic.ttf
        - asset: assets/font/product-sans-italic.ttf
        - asset: assets/font/product-sans-bold.ttf
        - asset: assets/font/product-sans-regular.ttf
